---
apiVersion: v1
kind: Service
metadata:
  name: travelservice
  namespace: kube-test
  labels:
    app: travel-service
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: travel-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelservice
  namespace: kube-test
  labels:
    app: travel-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-service
  template:
    metadata:
      labels:
        app: travel-service
    spec:
      containers:
        - name: travel-service
          image: 172.16.17.37:5000/hash-yang/travel-service:v1.1
          ports:
            - containerPort: 8083
          volumeMounts:
            - mountPath: /var/log/mclient
              name: log-volume
          env:
            - name: MCLUSTER_IP
              value: "172.16.17.37"
            - name: MCLUSTER_PORT
              value: "30761"
      volumes:
        - name: log-volume
          hostPath:
            path: /data/test-dir/log
